# Generated by Django 5.0 on 2023-12-10 14:49

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_created_at_employee_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='employees/employee.png', null=True, upload_to=main_app.models.unique_img_name),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
